name: mmriem_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0-278.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  flutter_secure_storage: ^9.0.0
  win32: ^5.12.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

web:
  renderer: canvaskit
  resources:
    - assets/images/
    - assets/icons/
