// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3WB_e2oOFmJGUDITBfLd-4_Pg9H6eQs',
    appId: '1:544706941106:web:3c49cb49d4e3d90af7f9ab',
    messagingSenderId: '544706941106',
    projectId: 'mamrimegolan',
    authDomain: 'mamrimegolan.firebaseapp.com',
    storageBucket: 'mamrimegolan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtj7jFGGE-FdQ9O6pT_w4T9JCZ58MGZPU',
    appId: '1:544706941106:android:25807396c97517ecf7f9ab',
    messagingSenderId: '544706941106',
    projectId: 'mamrimegolan',
    storageBucket: 'mamrimegolan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzafB6iEW46Pz0g3tK6Q3b_jhG4t0rK8M',
    appId: '1:544706941106:ios:2affb662d733300bf7f9ab',
    messagingSenderId: '544706941106',
    projectId: 'mamrimegolan',
    storageBucket: 'mamrimegolan.firebasestorage.app',
    iosBundleId: 'com.zvielkoren.mmriem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn3WB_e2oOFmJGUDITBfLd-4_Pg9H6eQs',
    appId: '1:544706941106:web:7f24b0af3e328827f7f9ab',
    messagingSenderId: '544706941106',
    projectId: 'mamrimegolan',
    authDomain: 'mamrimegolan.firebaseapp.com',
    storageBucket: 'mamrimegolan.firebasestorage.app',
  );
}
