name: Build Expo App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install EAS CLI
      run: npm install -g eas-cli
      
    - name: Configure EAS
      run: eas login --non-interactive --api-key ${{ secrets.EAS_API_KEY }}
      
    - name: Build Android
      run: eas build --platform android --non-interactive
      
    - name: Build iOS
      run: eas build --platform ios --non-interactive
      
    - name: Build Web
      run: |
        npm run build:web
        npm run export:web
        
    - name: Upload Android APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
        
    - name: Upload iOS IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-ipa
        path: ios/build/App.ipa
        if-no-files-found: error
        
    - name: Upload Web Build
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: web-build
        if-no-files-found: error 