name: Test Flutter App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: android
          - os: macos-latest
            platform: ios

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run Flutter tests
      run: flutter test
      
    - name: Run integration tests
      if: matrix.platform == 'android'
      run: |
        flutter emulators --launch Pixel_9_Pro_XL
        flutter test integration_test
        
    - name: Run integration tests
      if: matrix.platform == 'ios'
      run: |
        flutter emulators --launch apple_ios_simulator
        flutter test integration_test
        
    - name: Run web tests
      if: matrix.os == 'ubuntu-latest'
      run: |
        flutter test --platform chrome
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.platform }}
        path: test-results/
        if-no-files-found: ignore 